"""Durable sandbox Gmail double, stored only in the email module data directory."""
from __future__ import annotations

import itertools
import json
from pathlib import Path
from typing import Any

from hq.gmail.fake import FakeGmail


class FileFakeGmail(FakeGmail):
    def __init__(self, path: Path, address: str):
        super().__init__(address=address, scopes=("gmail.readonly", "gmail.send", "gmail.compose"))
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.parent.chmod(0o700)
        if path.exists():
            state = json.loads(path.read_text())
            if state.get("address") != address:
                raise ValueError("sandbox mailbox owner mismatch")
            self.messages = state["messages"]
            self.history_log = [tuple(h) for h in state["history_log"]]
            self.history_id = state["history_id"]
            self.min_history = state["min_history"]
            self.drafts = state["drafts"]
            self._ids = itertools.count(state["next_id"])
        else:
            self._next_id = 1
            self._save()

    def _save(self) -> None:
        # IDs are generated by FakeGmail's counter. Compute the next one from stored IDs
        # without consuming the counter.
        max_id = max((int(k[1:]) for k in self.messages if k[1:].isdigit()), default=0)
        max_id = max(max_id, *(int(d["id"][1:]) for d in self.drafts if d["id"][1:].isdigit()), 0)
        state: dict[str, Any] = {"address": self.address, "messages": self.messages,
                                 "history_log": self.history_log, "history_id": self.history_id,
                                 "min_history": self.min_history, "drafts": self.drafts,
                                 "next_id": max_id + 1}
        temp = self.path.with_suffix(".tmp")
        temp.write_text(json.dumps(state, ensure_ascii=False))
        temp.chmod(0o600)
        temp.replace(self.path)
        self.path.chmod(0o600)

    def _store(self, mid: str, raw: bytes, thread_id: str, labels: list[str], date_ms: int | None = None) -> str:
        result = super()._store(mid, raw, thread_id, labels, date_ms)
        self._save()
        return result

    async def create_draft(self, raw: bytes, thread_id: str | None = None) -> dict[str, Any]:
        result = await super().create_draft(raw, thread_id)
        self._save()
        return result
